# import it in config.yml
services:
    
    blog.twig.extension:
        class: "BlogBundle\\Twig\\BlogExtension"
        calls:
            - [setContainer, ["@service_container"] ]
        tags:
            - { name: twig.extension }

    blog_manager:
        class: "BlogBundle\\Service\\BlogManager"
        calls:
            - [setContainer, ["@service_container"] ]

    dynamic_relation_map.listener.doctrine_event_listener:
        class: "BlogBundle\\EventListener\\DynamicRelationSubscriber"
        arguments: ["%core.dynamic_discriminator_map.mapping%"]
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }